import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryProvider from "../provider/ReactQueryProvider";
import LayoutSite from '../components/layout/LayoutSite'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <LayoutSite>{children}</LayoutSite>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
<link
  href="https://fonts.googleapis.com/css?family=Dancing+Script:regular,500,600,700"
  rel="stylesheet"
/>;
